# Generated by Django 5.2.5 on 2025-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rfid_code',
            new_name='rfid',
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
